### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by yawenh** [aravind1338/506F20FinalProject#2]
Hi Aravind,

Here’s my feedback on your first draft. Hope it can be helpful.
1. Basic requirement:
	Overall, the report contains limited information, so I think you need to add more content to it. 
2. Introduction:
	I think you need to add an introduction part to introduce your motivation and briefly summarize your analysis process.
3. Data / Methods:
	The data source is showed in the report, but the variables used are not mentioned. The method part is too simple and needs to contain more details.
4. Results & conclusion:
	No results and conclusions showed in the report.
5. Code:
	All the code files are in the same folder in GitHub, which is good. Line length meets the requirement. The question in the header is clear. Maybe also show the data source here. For me, I think it is better to label your code step-by-step, which will make it easier to be read. 

I believe you will add more content to your report. And that’s all my advice for you based on your current version of code and writeup. Thanks.

Yawen

**Comment by aravind1338** [comment]
Thanks!
